use super::*;

#[derive(Debug, Clone, Serialize, ToSchema)]
pub struct McpToolInfo {
    pub name: &'static str,
    pub category: &'static str,
    pub description: &'static str,
    pub permission: &'static str,
    pub destructive: bool,
}

#[derive(Debug, Clone, Serialize, ToSchema)]
pub struct McpInfoResponse {
    pub enabled: bool,
    pub endpoint: &'static str,
    pub transport: &'static str,
    pub auth_header: &'static str,
    pub required_permission: Option<&'static str>,
    pub tools: Vec<McpToolInfo>,
}

impl McpInfoResponse {
    pub fn current() -> Self {
        Self {
            enabled: true,
            endpoint: "/mcp",
            transport: "streamable_http",
            auth_header: "X-API-Key",
            required_permission: None,
            tools: vec![
                McpToolInfo {
                    name: "system_status",
                    category: "system",
                    description: "读取面板版本与任务运行概况",
                    permission: "overview:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "tasks_list",
                    category: "tasks",
                    description: "搜索并筛选任务列表",
                    permission: "task:list",
                    destructive: false,
                },
                McpToolInfo {
                    name: "tasks_get",
                    category: "tasks",
                    description: "读取任务配置与当前状态",
                    permission: "task:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "tasks_get_logs",
                    category: "tasks",
                    description: "读取任务最新日志",
                    permission: "task:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "tasks_history",
                    category: "tasks",
                    description: "读取任务历史运行记录",
                    permission: "task:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "tasks_get_run_log",
                    category: "tasks",
                    description: "读取指定历史运行的日志",
                    permission: "task:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "tasks_create",
                    category: "tasks",
                    description: "创建任务",
                    permission: "task:create",
                    destructive: false,
                },
                McpToolInfo {
                    name: "tasks_update",
                    category: "tasks",
                    description: "更新任务配置",
                    permission: "task:update",
                    destructive: false,
                },
                McpToolInfo {
                    name: "tasks_delete",
                    category: "tasks",
                    description: "删除任务",
                    permission: "task:delete",
                    destructive: true,
                },
                McpToolInfo {
                    name: "tasks_run",
                    category: "tasks",
                    description: "启动任务",
                    permission: "task:run",
                    destructive: false,
                },
                McpToolInfo {
                    name: "tasks_stop",
                    category: "tasks",
                    description: "停止正在运行的任务",
                    permission: "task:stop",
                    destructive: true,
                },
                McpToolInfo {
                    name: "tasks_pause",
                    category: "tasks",
                    description: "暂停正在运行的任务",
                    permission: "task:stop",
                    destructive: false,
                },
                McpToolInfo {
                    name: "tasks_resume",
                    category: "tasks",
                    description: "恢复已暂停的任务",
                    permission: "task:stop",
                    destructive: false,
                },
                McpToolInfo {
                    name: "tasks_enable",
                    category: "tasks",
                    description: "启用任务调度",
                    permission: "task:update",
                    destructive: false,
                },
                McpToolInfo {
                    name: "tasks_disable",
                    category: "tasks",
                    description: "停用任务调度",
                    permission: "task:update",
                    destructive: true,
                },
                McpToolInfo {
                    name: "environments_list",
                    category: "environments",
                    description: "读取可用运行环境",
                    permission: "env:list",
                    destructive: false,
                },
                McpToolInfo {
                    name: "environments_get",
                    category: "environments",
                    description: "读取指定运行环境详情",
                    permission: "env:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "environments_versions",
                    category: "environments",
                    description: "读取可安装的 Python 和 Node.js 版本",
                    permission: "env:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "environments_packages_list",
                    category: "environments",
                    description: "读取运行环境或系统的软件包列表",
                    permission: "env:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "environments_create",
                    category: "environments",
                    description: "创建 Python 环境或安装 Node.js 版本",
                    permission: "env:create",
                    destructive: false,
                },
                McpToolInfo {
                    name: "environments_install_packages",
                    category: "environments",
                    description: "向运行环境或系统安装软件包",
                    permission: "env:update",
                    destructive: false,
                },
                McpToolInfo {
                    name: "environments_uninstall_package",
                    category: "environments",
                    description: "从运行环境或系统卸载软件包",
                    permission: "env:delete",
                    destructive: true,
                },
                McpToolInfo {
                    name: "environments_delete",
                    category: "environments",
                    description: "删除 Python 环境或卸载 Node.js 版本",
                    permission: "env:delete",
                    destructive: true,
                },
                McpToolInfo {
                    name: "environments_set_default",
                    category: "environments",
                    description: "设置系统默认 Node.js 版本",
                    permission: "env:update",
                    destructive: false,
                },
                McpToolInfo {
                    name: "variables_list",
                    category: "variables",
                    description: "列出变量元数据，不返回变量值",
                    permission: "var:list",
                    destructive: false,
                },
                McpToolInfo {
                    name: "variables_get",
                    category: "variables",
                    description: "读取指定变量及其敏感值",
                    permission: "var:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "variables_create",
                    category: "variables",
                    description: "创建变量",
                    permission: "var:create",
                    destructive: false,
                },
                McpToolInfo {
                    name: "variables_update",
                    category: "variables",
                    description: "更新变量",
                    permission: "var:update",
                    destructive: false,
                },
                McpToolInfo {
                    name: "variables_delete",
                    category: "variables",
                    description: "删除变量",
                    permission: "var:delete",
                    destructive: true,
                },
                McpToolInfo {
                    name: "audit_list",
                    category: "audit",
                    description: "读取最近的审计记录",
                    permission: "audit:list",
                    destructive: false,
                },
                McpToolInfo {
                    name: "files_list",
                    category: "files",
                    description: "列出脚本目录内容",
                    permission: "file:list",
                    destructive: false,
                },
                McpToolInfo {
                    name: "files_read",
                    category: "files",
                    description: "读取脚本文件内容",
                    permission: "file:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "files_write",
                    category: "files",
                    description: "写入脚本文件内容",
                    permission: "file:write",
                    destructive: true,
                },
                McpToolInfo {
                    name: "files_create_directory",
                    category: "files",
                    description: "创建脚本目录",
                    permission: "file:write",
                    destructive: false,
                },
                McpToolInfo {
                    name: "files_delete",
                    category: "files",
                    description: "删除脚本文件或目录",
                    permission: "file:delete",
                    destructive: true,
                },
                McpToolInfo {
                    name: "jobs_list",
                    category: "jobs",
                    description: "列出系统后台作业",
                    permission: "job:list",
                    destructive: false,
                },
                McpToolInfo {
                    name: "jobs_get",
                    category: "jobs",
                    description: "读取后台作业详情",
                    permission: "job:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "jobs_get_logs",
                    category: "jobs",
                    description: "读取后台作业日志",
                    permission: "job:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "jobs_cancel",
                    category: "jobs",
                    description: "取消正在运行的后台作业",
                    permission: "job:*",
                    destructive: true,
                },
                McpToolInfo {
                    name: "webhook_push",
                    category: "notifications",
                    description: "通过面板通知渠道推送消息",
                    permission: "webhook:push",
                    destructive: false,
                },
                McpToolInfo {
                    name: "share_station_stats",
                    category: "share",
                    description: "读取分享中转站容量与配置状态",
                    permission: "share:list",
                    destructive: false,
                },
                McpToolInfo {
                    name: "share_station_files",
                    category: "share",
                    description: "列出分享中转站文件，不返回密码",
                    permission: "share:list",
                    destructive: false,
                },
                McpToolInfo {
                    name: "share_import_sources",
                    category: "share",
                    description: "读取已导入任务的来源摘要",
                    permission: "share:list",
                    destructive: false,
                },
                McpToolInfo {
                    name: "git_repos_list",
                    category: "git",
                    description: "列出 Git 仓库及同步状态，不返回凭据",
                    permission: "git:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "git_repo_files",
                    category: "git",
                    description: "浏览指定 Git 仓库文件",
                    permission: "git:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "git_repo_scan_tasks",
                    category: "git",
                    description: "扫描指定 Git 仓库中的可导入任务",
                    permission: "git:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "git_repo_sync",
                    category: "git",
                    description: "同步指定 Git 仓库",
                    permission: "git:sync",
                    destructive: false,
                },
                McpToolInfo {
                    name: "system_releases",
                    category: "system",
                    description: "读取已安装的 Panel Release 与回退状态",
                    permission: "overview:read",
                    destructive: false,
                },
                McpToolInfo {
                    name: "system_update_check",
                    category: "system",
                    description: "按当前通道检查 Panel 更新",
                    permission: "overview:read",
                    destructive: false,
                },
            ],
        }
    }
}
