//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::task_status::TaskStatus;
use sea_orm::Set;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize, ToSchema)]
#[sea_orm(table_name = "tasks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub path: String,
    pub command: Option<String>,
    pub description: Option<String>,
    pub cron_schedule: Option<String>,
    pub enabled: bool,
    pub status: TaskStatus,
    pub pid: Option<i32>,
    pub notify: bool,
    #[schema(value_type = Option<Object>)]
    pub tags: Option<Json>,
    pub env_type: String,
    pub env_version: Option<String>,
    pub user_id: i32,
    #[schema(value_type = String, format = DateTime)]
    pub created_at: DateTimeUtc,
    #[schema(value_type = String, format = DateTime)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(column_type = "Text", nullable)]
    pub requirements: Option<String>,
    #[schema(value_type = Option<String>, format = DateTime)]
    pub last_finished_at: Option<DateTimeUtc>,
    #[schema(value_type = Option<String>, format = DateTime)]
    pub next_run_at: Option<DateTimeUtc>,
    pub cpu_limit: Option<i32>,
    pub timeout_sec: Option<i32>,
    pub memory_limit: Option<i32>,
    pub is_pinned: bool,
    #[schema(value_type = Option<Object>)]
    pub trigger_next_tasks: Option<Json>,
    pub import_source: Option<String>,
    pub remote_task_id: Option<String>,
    pub share_code: Option<String>,
    #[schema(value_type = Option<Object>)]
    pub random_config: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
    #[sea_orm(has_many = "super::task_runs::Entity")]
    TaskRuns,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::task_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskRuns.def()
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        self.updated_at = Set(chrono::Utc::now().into());
        if insert {
            self.created_at = Set(chrono::Utc::now().into());
        }
        Ok(self)
    }
}
