//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize, ToSchema)]
#[sea_orm(table_name = "variables")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub key: String,
    pub value: String,
    pub remarks: Option<String>,
    pub enabled: bool,
    pub scope: String,
    pub scope_id: Option<i32>,
    pub sort_order: i32,
    #[schema(value_type = String, format = DateTime)]
    pub created_at: DateTimeUtc,
    #[schema(value_type = String, format = DateTime)]
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::variables_tasks::Entity")]
    VariablesTasks,
}

impl Related<super::variables_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VariablesTasks.def()
    }
}

impl Related<super::tasks::Entity> for Entity {
    fn to() -> RelationDef {
        super::variables_tasks::Relation::Tasks.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::variables_tasks::Relation::Variables.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
