import type { WorkspaceAppDefinition } from "@/types/workspace";

export const workspaceApps: WorkspaceAppDefinition[] = [
  {
    id: "overview",
    title: "系统概览",
    icon: "i-ep-data-analysis",
    routeName: "overview",
    launchPolicy: "multi",
    mobileMode: "fullscreen",
  },
  {
    id: "tasks",
    title: "任务",
    icon: "i-carbon-task",
    routeName: "tasks",
    launchPolicy: "singleton",
    mobileMode: "fullscreen",
  },
  {
    id: "variables",
    title: "变量",
    icon: "i-ep-key",
    routeName: "variables",
    launchPolicy: "multi",
    mobileMode: "fullscreen",
  },
  {
    id: "files",
    title: "文件",
    icon: "i-ep-folder",
    routeName: "files",
    launchPolicy: "multi",
    mobileMode: "fullscreen",
  },
  {
    id: "environments",
    title: "环境",
    icon: "i-carbon-container-services",
    routeName: "environments",
    launchPolicy: "multi",
    mobileMode: "fullscreen",
  },
  {
    id: "share",
    title: "分享",
    icon: "i-carbon-share",
    routeName: "share",
    launchPolicy: "multi",
    mobileMode: "fullscreen",
  },
  {
    id: "extensions",
    title: "扩展",
    icon: "i-carbon-plug",
    routeName: "extensions",
    launchPolicy: "multi",
    mobileMode: "fullscreen",
  },
  {
    id: "git",
    title: "Git",
    icon: "i-ep-refresh",
    routeName: "git",
    launchPolicy: "multi",
    mobileMode: "fullscreen",
  },
  {
    id: "telegram",
    title: "Telegram",
    icon: "i-ep-promotion",
    routeName: "telegram",
    launchPolicy: "multi",
    mobileMode: "fullscreen",
  },
  {
    id: "terminal",
    title: "终端",
    icon: "i-carbon-terminal",
    routeName: "terminal",
    launchPolicy: "multi",
    mobileMode: "fullscreen",
  },
  {
    id: "settings",
    title: "设置",
    icon: "i-ep-setting",
    routeName: "settings",
    launchPolicy: "multi",
    mobileMode: "fullscreen",
  },
  {
    id: "more",
    title: "更多",
    icon: "i-ep-user",
    routeName: "more",
    launchPolicy: "multi",
    mobileMode: "fullscreen",
  },
  {
    id: "task-log",
    title: "任务日志",
    icon: "i-ep-monitor",
    launchPolicy: "multi",
    mobileMode: "stack",
  },
  {
    id: "task-editor",
    title: "任务编辑",
    icon: "i-ep-edit",
    launchPolicy: "multi",
    mobileMode: "stack",
  },
];

export const workspaceAppMap = new Map(
  workspaceApps.map((app) => [app.id, app]),
);
