#!/usr/bin/env node

let input = "";

process.stdin.setEncoding("utf8");
process.stdin.on("data", (chunk) => {
  input += chunk;
});

process.stdin.on("end", () => {
  let request;
  try {
    request = JSON.parse(input);
  } catch (error) {
    console.log(JSON.stringify({
      ok: false,
      error: { code: "invalid_json", message: String(error.message || error) },
    }));
    return;
  }

  const payload = request.input || {};
  if (request.action === "versions") {
    respond(request, { versions: ["3.10", "3.11", "3.12"] });
    return;
  }

  if (request.action === "encrypt") {
    const versions = Array.isArray(payload.versions) ? payload.versions.join(", ") : "";
    const header = [
      "# Generated by echo-compiler example plugin.",
      `# Function: ${payload.function_name || "main"}`,
      `# Versions: ${versions}`,
      "",
    ].join("\n");

    respond(request, {
      file_content: `${header}${payload.code || ""}\n`,
    });
    return;
  }

  console.log(JSON.stringify({
    request_id: request.request_id,
    ok: false,
    error: {
      code: "unsupported_action",
      message: `Unsupported action: ${request.action}`,
    },
  }));
});

function respond(request, output) {
  console.log(JSON.stringify({
    request_id: request.request_id,
    ok: true,
    output,
  }));
}
